# Generated by Django 4.2 on 2023-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(null=True)),
            ],
        ),
    ]
