# Generated by Django 4.2 on 2023-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
